#!/bin/bash

# Usage: ./wallpaper.sh /path/to/wallpaper.jpg
swww-daemon &
WALLPAPER=$1
GTK_THEME="oomox-pywal"

if [ -z "$WALLPAPER" ]; then
    echo "Usage: ./wallpaper.sh /path/to/wallpaper"
    exit 1
fi

if [ ! -f "$WALLPAPER" ]; then
    echo "File not found: $WALLPAPER"
    exit 1
fi

# Set wallpaper
swww img "$WALLPAPER" --transition-type fade --transition-duration 1

# Generate pywal colors
wal -i "$WALLPAPER" -n
source ~/.cache/wal/colors.sh
pkill waybar && waybar &disown
# Build oomox theme from pywal colors
OOMOX_THEME_SCRIPT=$(find /var/lib/flatpak -name "change_color.sh" 2>/dev/null | grep theme_oomox | head -1)

if [ -z "$OOMOX_THEME_SCRIPT" ]; then
    echo "Oomox not found!"
    exit 1
fi

OOMOX_COLORS=$(mktemp)
cat > "$OOMOX_COLORS" << COLORS
NAME=$GTK_THEME
BG=${color0#\#}
FG=${color15#\#}
MENU_BG=${color0#\#}
MENU_FG=${color15#\#}
SEL_BG=${color1#\#}
SEL_FG=${color15#\#}
TXT_BG=${color0#\#}
TXT_FG=${color15#\#}
BTN_BG=${color2#\#}
BTN_FG=${color15#\#}
HDR_BG=${color0#\#}
HDR_FG=${color15#\#}
ROUNDNESS=4
GRADIENT=0.0
SPACING=3
COLORS

"$OOMOX_THEME_SCRIPT" -o "$GTK_THEME" "$OOMOX_COLORS"
rm "$OOMOX_COLORS"
# Build oomox icons from pywal colors
OOMOX_ICONS_SCRIPT=$(find /var/lib/flatpak -name "change_color.sh" 2>/dev/null | grep icons_papirus | head -1)

if [ ! -z "$OOMOX_ICONS_SCRIPT" ]; then
    ICON_COLORS=$(mktemp)
    cat > "$ICON_COLORS" << COLORS
SEL_BG=${color1#\#}
SEL_FG=${color15#\#}
COLORS

    "$OOMOX_ICONS_SCRIPT" -o "oomox-pywal-icons" "$ICON_COLORS"
    sudo cp -rf ~/.icons/oomox-pywal-icons /usr/share/icons/
    rm "$ICON_COLORS"
fi
# Copy theme to /usr/share/themes so GTK can find it
sudo cp -rf ~/.themes/$GTK_THEME /usr/share/themes/

# Update hyprland.conf
sed -i "s|env = GTK_THEME,.*|env = GTK_THEME,$GTK_THEME|" ~/.config/hypr/hyprland.conf
sed -i "s|env = GTK2_RC_FILES,.*|env = GTK2_RC_FILES,/usr/share/themes/$GTK_THEME/gtk-2.0/gtkrc|" ~/.config/hypr/hyprland.conf

# Update env.conf if it exists
if [ -f ~/.config/hypr/env.conf ]; then
    sed -i "s|env = GTK_THEME,.*|env = GTK_THEME,$GTK_THEME|" ~/.config/hypr/env.conf
    sed -i "s|env = GTK2_RC_FILES,.*|env = GTK2_RC_FILES,/usr/share/themes/$GTK_THEME/gtk-2.0/gtkrc|" ~/.config/hypr/env.conf
fi

cat > ~/.local/share/nwg-look/gsettings << EOF
# Generated by nwg-look, do not edit this file.
gtk-theme=$GTK_THEME
icon-theme=oomox-pywal-icons
font-name=Noto Sans  10
cursor-theme=default
cursor-size=24
toolbar-style=text
toolbar-icons-size=large
font-hinting=slight
font-antialiasing=grayscale
font-rgba-order=rgb
text-scaling-factor=1.0
color-scheme=prefer-light
event-sounds=true
input-feedback-sounds=false
EOF
nwg-look -a

# Restart waybar


# Reload hyprland
hyprctl reload

echo "Done!"
